name = "NoahYixiaoHashCode"
uuid = "092416cb-42ad-489a-b523-ecbe260e3861"
authors = ["nmorale5 <nmorale5@mit.edu> and contributors"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
